### ISSUE TITLE
Lambda - Artifact not found before uploading to S3 if region not eu-west-1

### ISSUE THREAD

**Issue by mchv** [guardian/riff-raff#420]
I am trying to deploy in `us-east-1`an AWS lambda which is bundled as an `uber jar`, which for a reason I think have figured out (_not anymore_) is [failing on the first step](https://riffraff.gutools.co.uk/deployment/view/e6d7c6fa-3666-4828-9d9c-c91f87d50bb7), i.e finding the artifact in S3 to upload to the bucket.:

<img width="576" alt="screen shot 2017-01-26 at 12 13 29" src="https://cloud.githubusercontent.com/assets/615085/22330993/e78a595c-e3c0-11e6-9d8f-5003f7dfd12d.png">

- [Configuration seems OK to me](https://riffraff.gutools.co.uk/deployment/request/deployConfig?projectName=tools%3A%3Aaws-budgets&id=7) 
```yaml
stacks:
- aws-billing
regions:
- us-east-1
deployments:
  aws-budgets:
    type: aws-lambda
    parameters:
      fileName: aws-budgets-assembly-0.1.jar
      bucket: aws-billing-dist
      functions:
        PROD:
          name: AWS_Budgets
          filename: aws-budgets.jar
```

- [Artifacts seems OK to me](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=tools%3A%3Aaws-budgets&id=7) 

<img width="1211" alt="screen shot 2017-01-26 at 11 59 42" src="https://cloud.githubusercontent.com/assets/615085/22330621/1629f544-e3bf-11e6-8aab-bee99e0b7b65.png">

I have tried to reproduce the issue by adding a test in `magenta.deployment_type.LambdaTest`, but this is working as expected.

```scala
  it should "produce an S3 upload task (Mariot)" in {

  val data2: Map[String, JsValue] = Map(
    "bucket" -> JsString("aws-billing-dist"),
    "fileName" -> JsString("aws-budgets-assembly-0.1.jar"),
    "functionNames" -> Json.arr("MyFunction-")
  )

  val app2 = Seq(App("lambda"))
  val pkg2 = DeploymentPackage("lambda", app2, data2, "aws-lambda", S3Path("artifact-bucket", "test/123/lambda"), true,
    deploymentTypes)
  val defaultRegion2 = Region("us-east-1")



    val tasks = Lambda.actionsMap("uploadLambda").taskGenerator(pkg2, DeploymentResources(reporter, lookupEmpty, artifactClient), DeployTarget(parameters(PROD), NamedStack("aws-billing"), defaultRegion2))
    tasks should be (List(
      S3Upload(
        Region("us-east-1"),
        bucket = "aws-billing-dist",
        paths = Seq(S3Path("artifact-bucket", "test/123/lambda/aws-budgets-assembly-0.1.jar") -> s"aws-billing/PROD/lambda/aws-budgets-assembly-0.1.jar")
      )
    ))
  }

```

I have checked as well as `fileName` is parsed correctly, which had left me 🤔, thinking I had  missed something obvious until I realised that `S3Upload` is not intended for executing a transfer of a file cross-region!
